apiVersion: v1
kind: Service
metadata:
  name: es-transport
  labels:
    app: elasticsearch
    component: elasticsearch
spec:
  selector:
    component: elasticsearch
  ports:
    - protocol: TCP
      targetPort: 9300
      port: 9300
      name: transport
