apiVersion: v1
kind: Secret
metadata:
  name: store-config
stringData:
  DB_PASSWORD:
  DB_CONNECT_STRING:
  RABBITMQ_PASSWORD_API:
  RABBITMQ_PASSWORD_WORKER:
  LAJI_API_TOKEN:
  LAJI_API_DB_CONNECT_STRING:
  LAJI_API_DB_PASSWORD:

